services:
  app:
    build: ./app
    image: docker-tester-backend:latest
    ports:
      - "3001:3001"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  web:
    build: ./web
    image: docker-tester-frontend:latest
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/docker-compose.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - web 